<td class="style3" valign="top">

                    <div class="slidecontainer_open">
                        <div class="iconbox2heading">
                            <span id="news" class="headerToggle">
                                <img class="headerToggleImage"
                                    src="./images/minus.gif" /></span>Baqai Family
                        </div>
                        <div id="news_content" class="iconbox2contents"
                            style="display: block; top: 0px; left: -1px; height: 90px;">
                            &nbsp;&nbsp;<a href="./Default.aspx">Home</a><br />
                            &nbsp;&nbsp;<a href="./FamilyTree.aspx">Family Tree</a><br />
                            &nbsp;&nbsp;<a href="./AllMembers.aspx">All family members</a><br />
                        </div>
                    </div>
                    <br />
                    <div class="slidecontainer_open">
                        <div class="iconbox2heading">
                            <span id="Span1" class="headerToggle">
                                <img class="headerToggleImage"
                                    src="./images/minus.gif" /></span>Baqai Businesses
                        </div>
                        <div id="Div1" class="iconbox2contents"
                            style="display: block; top: 0px; left: -1px; height: 122px;">
                            &nbsp;&nbsp;<a href=".\Businesses.aspx">Hospitals/Clinics</a><br />
                            &nbsp;&nbsp;<a href=".\Businesses.aspx">Stores</a><br />
                            &nbsp;&nbsp;<a href=".\Businesses.aspx">Industries</a><br />
                            &nbsp;&nbsp;<a href=".\Businesses.aspx">Small Businesses</a><br />
                        </div>
                    </div>

                    <br />
                    <div class="slidecontainer_open">
                        <div class="iconbox2heading">
                            <span id="Span2" class="headerToggle">
                                <img class="headerToggleImage"
                                    src="./images/minus.gif" /></span>Baqai Professionals
                        </div>
                        <div id="Div2" class="iconbox2contents"
                            style="display: block; top: 0px; left: -1px; height: 216px;">
                            &nbsp;&nbsp;<a href="./AllMembers.aspx?OccupationId=1">Software Engineers</a><br />
                            &nbsp;&nbsp;<a href="./AllMembers.aspx?OccupationId=2">Electrical Engineers</a><br />
                            &nbsp;&nbsp;<a href="./AllMembers.aspx?OccupationId=3">Computer Engineers</a><br />
                            &nbsp;&nbsp;<a href="./AllMembers.aspx?OccupationId=4">Mechanical Engineers</a><br />
                            &nbsp;&nbsp;<a href="./AllMembers.aspx?OccupationId=7">Civil Engineers</a><br />
                            &nbsp;&nbsp;<a href="./AllMembers.aspx?OccupationId=5">Doctors</a><br />
                            &nbsp;&nbsp;<a href="./AllMembers.aspx?OccupationId=23">Hakeems</a><br />
                            &nbsp;&nbsp;<a href="./AllMembers.aspx?OccupationId=6">Teachers</a><br />
                            &nbsp;&nbsp;<a href="#">More coming soon</a>
                        </div>
                    </div>
                    <div class="slidecontainer_open">
                        <div class="iconbox2heading">
                            <span id="Span4" class="headerToggle">
                                <img class="headerToggleImage"
                                    src="./images/minus.gif" /></span>Stay Connected
                        </div>
                        <div id="Div4" class="iconbox2contents"
                            style="display: block; top: 0px; left: -1px; height: 100px;">
                                &nbsp;&nbsp;<a href="http://www.facebook.com/groups/BaqaiFamily/" target="_blank">Facebook</a><br />
                                &nbsp;&nbsp;<a href="http://groups.yahoo.com/group/baqai/" target="_blank">Yahoo Group</a><br />
                                &nbsp;&nbsp;<a href="mailto:BaqaiFamily@outlook.com" target="_top">Contact Us</a><br />
                                <br />
                                &nbsp;&nbsp;<a href="./SupportUs.aspx" target="_top">Contact Us</a><br />
                        </div>
                    </div>
                </td>